language: cpp

jobs:
  include:
  - stage: build
    os: linux
    dist: focal
    script:
      - cmake --version

  - stage: build
    os: osx
    osx_image: xcode11.5
    script:
      - "true"

  - stage: build
    os: windows
    script:
      - powershell scripts/build_windows.ps
